class TokenInfo:
    type: str
    string: str
    start: tuple[int, int]
    end: tuple[int, int]

    def is_exact_type(self, typ: str) -> bool: ...
    def loc_start(self) -> dict[str, int]: ...
    def loc_end(self) -> dict[str, int]: ...
    def loc(self) -> dict[str, int]: ...

def tokenize_str(s: str) -> list[TokenInfo]: ...
def tokenize_file(path: str) -> list[TokenInfo]: ...
